//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Models.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Degree.
        /// </summary>
        public static string AcademicDegree {
            get {
                return ResourceManager.GetString("AcademicDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Title.
        /// </summary>
        public static string AcademicTitle {
            get {
                return ResourceManager.GetString("AcademicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Time.
        /// </summary>
        public static string ActiveApplicationInfoViewModel_ArrivalTime {
            get {
                return ResourceManager.GetString("ActiveApplicationInfoViewModel_ArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ActiveApplicationInfoViewModel_Comment {
            get {
                return ResourceManager.GetString("ActiveApplicationInfoViewModel_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Hotel.
        /// </summary>
        public static string ActiveApplicationInfoViewModel_IsHotel {
            get {
                return ResourceManager.GetString("ActiveApplicationInfoViewModel_IsHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation Form.
        /// </summary>
        public static string ActiveApplicationInfoViewModel_ParticipationFormId {
            get {
                return ResourceManager.GetString("ActiveApplicationInfoViewModel_ParticipationFormId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Conference.
        /// </summary>
        public static string ActiveConference_Header {
            get {
                return ResourceManager.GetString("ActiveConference_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ApplicationOtherData_Comment {
            get {
                return ResourceManager.GetString("ApplicationOtherData_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time Of Arrival.
        /// </summary>
        public static string ApplicationOtherData_EstimatedTimeOfArrival {
            get {
                return ResourceManager.GetString("ApplicationOtherData_EstimatedTimeOfArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Of Participation.
        /// </summary>
        public static string ApplicationOtherData_FormOfParticipation {
            get {
                return ResourceManager.GetString("ApplicationOtherData_FormOfParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need For Reservation.
        /// </summary>
        public static string ApplicationOtherData_NeedForReservation {
            get {
                return ResourceManager.GetString("ApplicationOtherData_NeedForReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement Fee.
        /// </summary>
        public static string ArrangementFee_Header {
            get {
                return ResourceManager.GetString("ArrangementFee_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions Of Participation.
        /// </summary>
        public static string ConditionsOfParticipation_Header {
            get {
                return ResourceManager.GetString("ConditionsOfParticipation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief Information.
        /// </summary>
        public static string ConferenceSummaryInfoViewModel_BriefInformation {
            get {
                return ResourceManager.GetString("ConferenceSummaryInfoViewModel_BriefInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Point.
        /// </summary>
        public static string ConferenceSummaryInfoViewModel_MeetingPoint {
            get {
                return ResourceManager.GetString("ConferenceSummaryInfoViewModel_MeetingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Conference.
        /// </summary>
        public static string ConferenceSummaryInfoViewModel_NameOfConference {
            get {
                return ResourceManager.GetString("ConferenceSummaryInfoViewModel_NameOfConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation Forms.
        /// </summary>
        public static string ConferenceSummaryInfoViewModel_ParticipationForms {
            get {
                return ResourceManager.GetString("ConferenceSummaryInfoViewModel_ParticipationForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string ConferenceSummaryInfoViewModel_StartDate {
            get {
                return ResourceManager.GetString("ConferenceSummaryInfoViewModel_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create An Report.
        /// </summary>
        public static string CreateAnReportBytton {
            get {
                return ResourceManager.GetString("CreateAnReportBytton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateConferenceButton {
            get {
                return ResourceManager.GetString("CreateConferenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create conference.
        /// </summary>
        public static string CreateConferenceHeader {
            get {
                return ResourceManager.GetString("CreateConferenceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for conference.
        /// </summary>
        public static string DetailsOfTheConferenceViewModel_RegisterButton {
            get {
                return ResourceManager.GetString("DetailsOfTheConferenceViewModel_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have a local account.
        /// </summary>
        public static string DontHaveLocalAccountText {
            get {
                return ResourceManager.GetString("DontHaveLocalAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is not a valid e-mail address..
        /// </summary>
        public static string EmailAdressNotValid {
            get {
                return ResourceManager.GetString("EmailAdressNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {1} characters..
        /// </summary>
        public static string FieldLong {
            get {
                return ResourceManager.GetString("FieldLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can not be shorter than  {2} symbols.
        /// </summary>
        public static string FieldMinLong {
            get {
                return ResourceManager.GetString("FieldMinLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FilesOfConferenceJqGridModel_Description {
            get {
                return ResourceManager.GetString("FilesOfConferenceJqGridModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FilesOfConferenceJqGridModel_Name {
            get {
                return ResourceManager.GetString("FilesOfConferenceJqGridModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string FilesOfConferenceJqGridModel_Path {
            get {
                return ResourceManager.GetString("FilesOfConferenceJqGridModel_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Conditions.
        /// </summary>
        public static string FinancialConditions_Header {
            get {
                return ResourceManager.GetString("FinancialConditions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Of Participation.
        /// </summary>
        public static string FormOfParticipation_FormOfParticipationName {
            get {
                return ResourceManager.GetString("FormOfParticipation_FormOfParticipationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string HelloOneText {
            get {
                return ResourceManager.GetString("HelloOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for conference.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №.
        /// </summary>
        public static string KeyDates_DateId {
            get {
                return ResourceManager.GetString("KeyDates_DateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string KeyDates_Description {
            get {
                return ResourceManager.GetString("KeyDates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string KeyDates_EndDate {
            get {
                return ResourceManager.GetString("KeyDates_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string KeyDates_StartDate {
            get {
                return ResourceManager.GetString("KeyDates_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Of Conference.
        /// </summary>
        public static string LanguagesConference_LanguageName {
            get {
                return ResourceManager.GetString("LanguagesConference_LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore_Button {
            get {
                return ResourceManager.GetString("LearnMore_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string LocalAccountToLogInText {
            get {
                return ResourceManager.GetString("LocalAccountToLogInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogInBarName {
            get {
                return ResourceManager.GetString("LogInBarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in as.
        /// </summary>
        public static string LogInMessage {
            get {
                return ResourceManager.GetString("LogInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogInTitle {
            get {
                return ResourceManager.GetString("LogInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextButtonName {
            get {
                return ResourceManager.GetString("NextButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string OrganizingCommittee_Address {
            get {
                return ResourceManager.GetString("OrganizingCommittee_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string OrganizingCommittee_ContactInformation {
            get {
                return ResourceManager.GetString("OrganizingCommittee_ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string OrganizingCommittee_Email {
            get {
                return ResourceManager.GetString("OrganizingCommittee_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string OrganizingCommittee_Phone {
            get {
                return ResourceManager.GetString("OrganizingCommittee_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been successfully saved.
        /// </summary>
        public static string OrganizingCommittee_SuccessMessage {
            get {
                return ResourceManager.GetString("OrganizingCommittee_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Infirmation.
        /// </summary>
        public static string OrganizingCommitteeMembers_AdditionalInformation {
            get {
                return ResourceManager.GetString("OrganizingCommitteeMembers_AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string OrganizingCommitteeMembers_FullName {
            get {
                return ResourceManager.GetString("OrganizingCommitteeMembers_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Number.
        /// </summary>
        public static string OrganizingCommitteeMembers_IndexNumber {
            get {
                return ResourceManager.GetString("OrganizingCommitteeMembers_IndexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string OrganizingCommitteeMembers_Name {
            get {
                return ResourceManager.GetString("OrganizingCommitteeMembers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        public static string OrganizingCommitteeMembers_Patronymic {
            get {
                return ResourceManager.GetString("OrganizingCommitteeMembers_Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string OrganizingCommitteeMembers_Post {
            get {
                return ResourceManager.GetString("OrganizingCommitteeMembers_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string OrganizingCommitteeMembers_Surname {
            get {
                return ResourceManager.GetString("OrganizingCommitteeMembers_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Time.
        /// </summary>
        public static string ParticipantsConference_ArrivalTime {
            get {
                return ResourceManager.GetString("ParticipantsConference_ArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ParticipantsConference_Comment {
            get {
                return ResourceManager.GetString("ParticipantsConference_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Of Participation.
        /// </summary>
        public static string ParticipantsConference_FormOfParticipation {
            get {
                return ResourceManager.GetString("ParticipantsConference_FormOfParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string ParticipantsConference_FullName {
            get {
                return ResourceManager.GetString("ParticipantsConference_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Hostel.
        /// </summary>
        public static string ParticipantsConference_IsHostel {
            get {
                return ResourceManager.GetString("ParticipantsConference_IsHostel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; do not match..
        /// </summary>
        public static string PasswordCompare {
            get {
                return ResourceManager.GetString("PasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        public static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        public static string PersonalInfo_Headrr {
            get {
                return ResourceManager.GetString("PersonalInfo_Headrr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterBarName {
            get {
                return ResourceManager.GetString("RegisterBarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string RegisterForConference_Stab1 {
            get {
                return ResourceManager.GetString("RegisterForConference_Stab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms of participation and Catering.
        /// </summary>
        public static string RegisterForConference_Stab2 {
            get {
                return ResourceManager.GetString("RegisterForConference_Stab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterLabel {
            get {
                return ResourceManager.GetString("RegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new user.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements For Registration.
        /// </summary>
        public static string RequirementsForRegistration_Header {
            get {
                return ResourceManager.GetString("RequirementsForRegistration_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ResearchAreas_AddResearch_Button {
            get {
                return ResourceManager.GetString("ResearchAreas_AddResearch_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors Report.
        /// </summary>
        public static string ResearchAreas_AuthorsReport {
            get {
                return ResourceManager.GetString("ResearchAreas_AuthorsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date And Time.
        /// </summary>
        public static string ResearchAreas_DateTime {
            get {
                return ResourceManager.GetString("ResearchAreas_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ResearchAreas_Description {
            get {
                return ResourceManager.GetString("ResearchAreas_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Number.
        /// </summary>
        public static string ResearchAreas_IndexNumber {
            get {
                return ResourceManager.GetString("ResearchAreas_IndexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ResearchAreas_Name {
            get {
                return ResourceManager.GetString("ResearchAreas_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Report.
        /// </summary>
        public static string ResearchAreas_NameOfReport {
            get {
                return ResourceManager.GetString("ResearchAreas_NameOfReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path To Check.
        /// </summary>
        public static string ResearchAreas_PathToCheck {
            get {
                return ResourceManager.GetString("ResearchAreas_PathToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path To Report.
        /// </summary>
        public static string ResearchAreas_PathToReport {
            get {
                return ResourceManager.GetString("ResearchAreas_PathToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        public static string ResearchAreas_Venue {
            get {
                return ResourceManager.GetString("ResearchAreas_Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonName {
            get {
                return ResourceManager.GetString("SaveButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief Information.
        /// </summary>
        public static string Summary_BriefInformation {
            get {
                return ResourceManager.GetString("Summary_BriefInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of The Conference.
        /// </summary>
        public static string Summary_NameOfTheConference {
            get {
                return ResourceManager.GetString("Summary_NameOfTheConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Summary_StartDate {
            get {
                return ResourceManager.GetString("Summary_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        public static string Summary_Venue {
            get {
                return ResourceManager.GetString("Summary_Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SummaryInfoStabTitle {
            get {
                return ResourceManager.GetString("SummaryInfoStabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        public static string UserAccount_Header {
            get {
                return ResourceManager.GetString("UserAccount_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors Report.
        /// </summary>
        public static string UserReportsViewModel_AuthorsReport {
            get {
                return ResourceManager.GetString("UserReportsViewModel_AuthorsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Report.
        /// </summary>
        public static string UserReportsViewModel_NameOfReport {
            get {
                return ResourceManager.GetString("UserReportsViewModel_NameOfReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path To Check.
        /// </summary>
        public static string UserReportsViewModel_PathToCheck {
            get {
                return ResourceManager.GetString("UserReportsViewModel_PathToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path To Report.
        /// </summary>
        public static string UserReportsViewModel_PathToReport {
            get {
                return ResourceManager.GetString("UserReportsViewModel_PathToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Areas.
        /// </summary>
        public static string UserReportsViewModel_ResearchAreas {
            get {
                return ResourceManager.GetString("UserReportsViewModel_ResearchAreas", resourceCulture);
            }
        }
    }
}
