//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationStatus
    {
        public ApplicationStatus()
        {
            this.Application = new HashSet<Application>();
        }
    
        public int ApplicationStatusId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
    }
}
