//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.AnswersQuestions = new HashSet<AnswersQuestions>();
            this.Report = new HashSet<Report>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public Nullable<bool> IsHotel { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public string Comment { get; set; }
        public int ParticipationFormId { get; set; }
        public int ConferenceId { get; set; }
        public System.Guid UserId { get; set; }
        public int ApplicationStatusId { get; set; }
    
        public virtual ICollection<AnswersQuestions> AnswersQuestions { get; set; }
        public virtual ParticipationForms ParticipationForms { get; set; }
        public virtual Users Users { get; set; }
        public virtual Conferences Conferences { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        public virtual ICollection<Report> Report { get; set; }
    }
}
