//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckStatus
    {
        public CheckStatus()
        {
            this.Check = new HashSet<Check>();
        }
    
        public int CheckStatusId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Check> Check { get; set; }
    }
}
