//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public System.Guid CheckId { get; set; }
        public string PathCheck { get; set; }
        public Nullable<System.DateTime> TimePayment { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public string Comment { get; set; }
        public int StatusId { get; set; }
        public System.Guid ReportId { get; set; }
    
        public virtual CheckStatus CheckStatus { get; set; }
        public virtual Report Report { get; set; }
    }
}
