//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceForms
    {
        public int ConferenceFormId { get; set; }
        public int ConferenceId { get; set; }
        public int ParticipationFormId { get; set; }
    
        public virtual ParticipationForms ParticipationForms { get; set; }
        public virtual Conferences Conferences { get; set; }
    }
}
