//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceStatus
    {
        public System.Guid ConferenceStatusId { get; set; }
        public int StatusesId { get; set; }
        public System.DateTime DateChange { get; set; }
        public int ConferenceId { get; set; }
    
        public virtual Conferences Conferences { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
