//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECDatabaseEntities : DbContext
    {
        public ECDatabaseEntities()
            : base("name=ECDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ConferenceForms> ConferenceForms { get; set; }
        public virtual DbSet<FilesConference> FilesConference { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<AnswersQuestions> AnswersQuestions { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Check> Check { get; set; }
        public virtual DbSet<CheckStatus> CheckStatus { get; set; }
        public virtual DbSet<KeyDates> KeyDates { get; set; }
        public virtual DbSet<LanguagesConference> LanguagesConference { get; set; }
        public virtual DbSet<ParticipationForms> ParticipationForms { get; set; }
        public virtual DbSet<ResearchAreas> ResearchAreas { get; set; }
        public virtual DbSet<UsersMessages> UsersMessages { get; set; }
        public virtual DbSet<OrganizingCommittee> OrganizingCommittee { get; set; }
        public virtual DbSet<OrganizingCommitteeMembers> OrganizingCommitteeMembers { get; set; }
        public virtual DbSet<Conferences> Conferences { get; set; }
        public virtual DbSet<ConferenceStatus> ConferenceStatus { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<ApplicationStatus> ApplicationStatus { get; set; }
        public virtual DbSet<Report> Report { get; set; }
    }
}
