//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public Messages()
        {
            this.UsersMessages = new HashSet<UsersMessages>();
        }
    
        public System.Guid MessageId { get; set; }
        public string Message { get; set; }
        public Nullable<int> ConferenceId { get; set; }
    
        public virtual ICollection<UsersMessages> UsersMessages { get; set; }
        public virtual Conferences Conferences { get; set; }
    }
}
