//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizingCommitteeMembers
    {
        public System.Guid OrganizingCommitteeMemberId { get; set; }
        public string Post { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string AdditionalInformation { get; set; }
        public int OrganizingCommitteeId { get; set; }
    
        public virtual OrganizingCommittee OrganizingCommittee { get; set; }
    }
}
