//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizingCommittee
    {
        public OrganizingCommittee()
        {
            this.OrganizingCommitteeMembers = new HashSet<OrganizingCommitteeMembers>();
        }
    
        public int OrganizingCommitteeId { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int ConferenceId { get; set; }
    
        public virtual ICollection<OrganizingCommitteeMembers> OrganizingCommitteeMembers { get; set; }
        public virtual Conferences Conferences { get; set; }
    }
}
