//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationForms
    {
        public ParticipationForms()
        {
            this.Application = new HashSet<Application>();
            this.ConferenceForms = new HashSet<ConferenceForms>();
        }
    
        public int ParticipationFormId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
        public virtual ICollection<ConferenceForms> ConferenceForms { get; set; }
    }
}
