//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.Check = new HashSet<Check>();
        }
    
        public System.Guid ReportId { get; set; }
        public string NameReport { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string PathReport { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public int ResearchAreasId { get; set; }
        public string AuthorsReport { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<Check> Check { get; set; }
        public virtual ResearchAreas ResearchAreas { get; set; }
    }
}
