//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchAreas
    {
        public ResearchAreas()
        {
            this.Report = new HashSet<Report>();
        }
    
        public int ResearchAreasId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
        public string Venue { get; set; }
        public string Description { get; set; }
        public int ConferenceId { get; set; }
    
        public virtual Conferences Conferences { get; set; }
        public virtual ICollection<Report> Report { get; set; }
    }
}
