//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Application = new HashSet<Application>();
            this.UsersMessages = new HashSet<UsersMessages>();
        }
    
        public System.Guid UserId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Password { get; set; }
        public string AcademicDegree { get; set; }
        public string Email { get; set; }
        public string AcademicTitle { get; set; }
        public string Organization { get; set; }
        public string Address { get; set; }
        public int Phone { get; set; }
        public int RoleId { get; set; }
    
        public virtual UserRoles UserRoles { get; set; }
        public virtual ICollection<Application> Application { get; set; }
        public virtual ICollection<UsersMessages> UsersMessages { get; set; }
    }
}
